spring:
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${PATH_ai_aliyun_api}
      chat:
        options:
          model: qwen3.8-flash
      embedding:
        options:
          model: qwen3.7-text-embedding
          dimensions: 1024
          encoding-format: float
    vectorstore:
      redis:
        initialize-schema: true
        index-name: spring-ai-index
        prefix: "emb:"
  config:
    import: classpath:session.yml
logging:
  level:
    org.springframework.ai: info
    org.springframework.ai.chat.client: info
image:
  max-width: 2048
  max-height: 2048
system:
  chat:
    file: classpath:system-message.txt

