spring:
  ai:
    openai:
      base-url: ${flower.ai.base-url}
      api-key: ${flower.ai.api-key}
      chat:
        options:
          model: ${flower.ai.chat.model}
      embedding:
        options:
          model: ${flower.ai.embedding.model}
          dimensions: 1024
          encoding-format: float

  config:
    import: classpath:session.yml

system:
  chat:
    file: classpath:system-message.txt
    group: DEFAULT_GROUP
    timeout-ms: 20000

